version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    environment:
        # - "NEXT_PUBLIC_API_URL=http://my.xyz.scd"
        - NEXT_PUBLIC_API_URL=http://localhost:6000
    ports: 
      - "3000:3000"
  api-server:
    image: api-server
    ports:
      - "5000:5000"