version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    environment: 
      - PORT=3000
      - API_URL=http://localhost:5000
      - AUTH0_SECRET=77d4ba7d83cdddb3fbee39b6e2d25e9b6c297466e72008d055b9899f36572ec9
      - AUTH0_BASE_URL=http://localhost:3000
      - AUTH0_ISSUER_BASE_URL=https://dev-ccl69nx0.auth0.com
      - AUTH0_CLIENT_ID=cAItSQllt3xEq5Y6zQJMH7C7AgFswOue
      - AUTH0_CLIENT_SECRET=vlzcgvAxAyg2PGTRcT27y7TSSbLIBLIUgw6RKijcjZel-xpCxgx1X8hfISwlDpVH
    ports: 
      - "3000:3000"
  api-server:
    image: api-server
    ports:
      - "5000:5000"